./results/race_food.png: ./scripts/race_food_analysis.R ./results/race_food_analysis_tmp.txt
	Rscript ./scripts/race_food_analysis.R

./results/race_food_analysis_tmp.txt: ./scripts/race_food_distribution.py
	python ./scripts/race_food_distribution.py


